name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Установите Node.js версии 20

      - name: Install dependencies
        run: |
          cd frontend
          npm install || (cat npm-debug.log && exit 1)

      - name: Run ESLint
        run: |
          cd frontend
          npm run lint

  format:
    runs-on: ubuntu-latest
    needs: lint  # Запускаем после успешного завершения задачи lint
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Установите Node.js версии 20

      - name: Install dependencies
        run: |
          cd frontend
          npm install || (cat npm-debug.log && exit 1)

      - name: Run Prettier
        run: |
          cd frontend
          npm run format -- --write  # Автоматически исправляем форматирование

      - name: Run ESLint (fix)
        run: |
          cd frontend
          npm run lint -- --fix  # Автоматически исправляем ошибки линтера

          - name: Commit changes
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            cd frontend
            git config user.name "temirzzz1201"
            git config user.email "temir1201@mail.ru"
            git add .
            git commit -m "chore: format code" || echo "No changes to commit"
            git push https://x-access-token:${GITHUB_TOKEN}@github.com/temirzzz1201/express-next-app.git HEAD:main


  build:
    runs-on: ubuntu-latest
    needs: format  # Запускаем после успешного завершения задачи format
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Установите Node.js версии 20

      - name: Install dependencies
        run: |
          cd frontend
          npm install || (cat npm-debug.log && exit 1)

      - name: Build project
        run: |
          cd frontend
          npm run build
